apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "botchart.fullname" . }}
  labels:
    {{- include "botchart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "botchart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "botchart.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "botchart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: "DB_URL"
              valueFrom:
                secretKeyRef:
                  name: {{ include "botchart.fullname" . }}
                  key: dbUrl
            - name: "BOT_TOKEN"
              valueFrom:
                secretKeyRef:
                  name: {{ include "botchart.fullname" . }}
                  key: botToken
            - name: "CHANNEL_ID"
              valueFrom:
                secretKeyRef:
                  name: {{ include "botchart.fullname" . }}
                  key: channelId
            - name: "GSAPI_ID"
              valueFrom:
                secretKeyRef:
                  name: {{ include "botchart.fullname" . }}
                  key: googleSheetsID
            - name: "GSAPI_SERVICE_KEY"
              valueFrom:
                secretKeyRef:
                  name: {{ include "botchart.fullname" . }}
                  key: googleSheetsServiceKey
          ports:
            - name: http
              containerPort: 80
              hostPort: 8080
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - python3
                - /app/bot/helth/helth_check.py
                - {{ .Values.botAuth.token }}

            initialDelaySeconds: 20
            periodSeconds: 5
          readinessProbe:
            exec:
              command:
                - python3
                - /app/bot/helth/helth_check.py
                - {{ .Values.botAuth.token }}

            initialDelaySeconds: 20
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
