apiVersion: v1
kind: Secret
metadata:
  name: {{ include "botchart.fullname" . }}
type: Opaque
stringData:
  botToken: {{ .Values.botAuth.token }}
  channelId: {{ .Values.botAuth.channelId | quote }}
  dbUrl: postgresql+asyncpg://{{ .Values.postgresql.auth.username }}:{{ .Values.postgresql.auth.password }}@{{ .Release.Name }}-postgresql:5432/{{ .Values.postgresql.auth.database }}
  googleSheetsID: {{ .Values.googleSheets.Id }}
  googleSheetsServiceKey: |
    {
    {{- range $key, $val := .Values.googleSheets.ServiceKey }}
      "{{ $key }}":"{{ $val -}}"
    {{- end }}
    }


